# Generated by Re‑Photo Booth migration script

from django.db import migrations, models
import django.db.models.deletion
import uuid
import photobooth.models


class Migration(migrations.Migration):
    """
    Initial migration for the photobooth app.

    Creates the Theme, Event, Booth and Photo models with fields
    corresponding to the application requirements.  The upload path for
    photos uses the ``photo_upload_to`` helper from ``photobooth.models``.
    """

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('primary_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('secondary_color', models.CharField(default='#000000', max_length=7)),
                ('font_family', models.CharField(default='system-ui, sans-serif', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='events/logos/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='events/backgrounds/')),
                ('overlay_frame', models.ImageField(blank=True, null=True, upload_to='events/overlays/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photobooth.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photobooth.event')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to=photobooth.models.photo_upload_to)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='photos/qr/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='photobooth.booth')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='photobooth.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]